### ISSUE TITLE
drawing.js does not load to page

### ISSUE THREAD

**Issue by LukeLentz** [FlynnHorrell/WebAppsProject#7]
i don't know how to get svg.js files to load to the web page. I didn't see anything in the documentation, and other tutorials are written for standard svg. 

@skiadas

**Comment by skiadas** [comment]
You should be able to load svg.js the same way you are loading jquery, by setting it in the path. Did that not work?

**Comment by LukeLentz** [comment]
I set the path to this
       "drawing": "../drawing"

and get this error from the console
 Uncaught TypeError: Cannot read property 'nodeName' of null   svg.js: 2592

The line in svg.js it is complaining about is this
 this.constructor
        .call(this, this.parent.nodeName == 'svg' ? this.parent : SVG.create('svg'))

I don't know what's wrong with it, I didn't change anything before putting svg.js into the lib folder. The path for svg.js should be correct, I formatted it the same as the one for jquery

@skiadas

**Comment by LukeLentz** [comment]
I sometimes get this error in the console if I reload a few times, even without changing anything
Uncaught ReferenceError: SVG is not defined   drawing.js: 3

@skiadas

**Comment by skiadas** [comment]
Hm I can't really reproduce this. When I checked out your project I was able to load the index.html file with no errors. Do you have any local commits that are not pushed yet? 

Do I understand correctly that your local code somehow tries to load the file called drawing.js in your main folder? Cause that file doesn't seem to be set up for AMD, it would probably load out of turn and run too early.

**Comment by LukeLentz** [comment]
I forgot to commit
@skiadas

**Comment by skiadas** [comment]
Yep I see now. You shouldn't put "drawing" in the paths area. It is your own code, you should wrap it in a define and load it the same way you load things like controller.

Another key idea is to make it so that the file "drawing" doesn't do any drawing right away, but it returns a function that when called will do the drawing. Then capture that function as the value returned by "drawing", so at the argument after svg in line 22 of main.js, and call that function inside this block:

```
$(function() {
      console.log("Page loaded!");
   });
```

In general what you put inside there is code that you want to run only once all the elements are in place. Any code that messes with the UI should really be in there.

**Comment by LukeLentz** [comment]
I changed it to a function and put a define into drawing.js. There are no errors, but the graphics aren't showing up on the page either. The console shows the function being called.
@skiadas

**Comment by skiadas** [comment]
Hm no the function isn't being called, you would need to do "drawing.new()" for that and I don't think any part of your code does that.

But the other problem you have, I think, is that you don't have an element in the page whose id is "drawing". Something like `<div id="drawing"></div>` on the html page, for it to use as the container for the svg. Without it, I'm not sure what `var draw = SVG("drawing").size(104, 480);` will do. The documentation for SVG (http://documentup.com/wout/svg.js) seems to suggest you need to give it either an existing element or the id of an existing element. Otherwise it basically has no idea where in the page you want it to insert the SVG.
