### ISSUE TITLE
Get svg graphics to contain buttons

### ISSUE THREAD

**Issue by LukeLentz** [FlynnHorrell/WebAppsProject#8]
Make the svg graphics also be buttons, so that the user can click on the strings to make chords rather than using the buttons that we currently have. 

@skiadas

**Comment by LukeLentz** [comment]
I can get the svg elements to call functions on click, but the only way I can see this working the way I want it is to have 72 lines representing each possible combination of string and fret, and then hard-coding a call to setFret on whichever string was clicked for that fret. That sounds like too much effort, and I feel like there is a better way of doing it. 

@skiadas

**Comment by skiadas** [comment]
Hm, can you generate those lines in a double for loop or something like that? Maybe I'm not understanding the problem very well, what part do you need to "hard-code"? Is the call to setFret not the same for each fret, just the value changing? All you'll have to do is store that value in a data-attribute when you create the lines, hopefully in some sort of for loop. But maybe I'm missing the point, I'm not quite up to speed with your code.

**Comment by LukeLentz** [comment]
I cannot get it to work in a for loop. I have to generate them manually.
@skiadas

**Comment by LukeLentz** [comment]
I don't know if I can put the svg elements into an array. The arrays in svg.js are for a different problem.

**Comment by skiadas** [comment]
If you can put them in a variable, you can put them in an array. All the code you have in drawing.js is Javascript code, these are Javascript values, you can do with them whatever you can do with any other values.

Technically they are not svg elements themselves, they are wrappers around svg elements, that svg.js implements. They are in fact regular old Javascript objects. Otherwise you couldn't write the kinds of calls you do write in drawing.js

**Comment by LukeLentz** [comment]
I tried putting them all in at once, but I got an unexpected token: var error. Do I need to push them into the array individually, or give all the lines a unique name?

**Comment by skiadas** [comment]
You should be able to do something like this:

```
var arr = [
     draw.line(0, 2, 533, 2).stroke({color: '#c0c0c0', width: 2 }),
     ....
];
```

So no semicolons, and no var assignments in each line.

**Comment by LukeLentz** [comment]
Since drawing() returns both the string and fret graphics, should I put them into two different files or is there a way I can isolate the array?

**Comment by skiadas** [comment]
You can have "drawing" return an object with multiple items. Different files sounds good too if those two don't need to know about each other.

**Comment by LukeLentz** [comment]
Will the object be returned along with the makeDrawing function? I'm also not sure how to get the item I want from main. Whenver I try to access the object, I get TypeError: Cannot read property 'o' of undefined

**Comment by skiadas** [comment]
Right, the makeDrawing function will be just one property of that object. Then the value of "drawing" in your main will be an object containing all these useful parts to it.

**Comment by LukeLentz** [comment]
I can get it all to return, but in main I get the error TypeError: object is not a function

**Comment by LukeLentz** [comment]
The console log shows each item in the object as being undefined

**Comment by skiadas** [comment]
Your drawing.js still returns only the function:  `return makeDrawing;`  
You need instead to return an object that has in it all the components you need. The only way to pass information between modules is via the `return` at the end of each module.

**Comment by LukeLentz** [comment]
I just commited the recent changes.

**Comment by skiadas** [comment]
Good, now in your "main.js, the value of `drawing` is exactly this object `o`. So you would do `drawing.a`, `drawing.b`, `drawing.c`.

Whatever you return in drawing.js is what the value of `drawing` will have in main.js.

**Comment by LukeLentz** [comment]
If I change the value of c from makeDrawing to makeDrawing(), the svg graphics will show up, but not the other buttons. I also get a typeError for line 112 in drawing. As it currently is, the console log shows all properties of o as undefined and the svg is not appearing.

**Comment by skiadas** [comment]
No you shouldn't change the value of c, the value of c is fine.

Oh I see the main problem, I don't htink you're creating the object `o` correctly. You don't need `Object.create`, you can simply do:

```
var o = {
   a: ...,
   b: ...,
};
```

You can't use Object.create, it isn't going to do the right thing in this case. The documentation of it will show you what's wrong, but just don't use it for this case. The way to create objects is just by putting the properties around braces.

**Comment by LukeLentz** [comment]
I've done that, but the console logs seem to show empty arrays for properties a and b. The svg is still not showing on the screen unless I put parentheses after makeDrawing.
@skiadas

**Comment by skiadas** [comment]
Ooh I see what's going on now, the frets and strings are created inside the makeDrawing function. And that is not called till later, and isn't returning anything. Ok so new plan:
- Currently your makeDrawing function does not return anything, it just ends in line 109. Make it instead return an object with frets and strings.
- Instead of returning the object o at line 115 (which is what your "drawing.js" returns, make it return the function makeDrawing (uncalled).
- in your main.js, call "drawing()" and store the result in a variable. That variable will now have the object with the frets and strings.

**Comment by LukeLentz** [comment]
It's working now, but I forget how I was supposed to get the svg stuff to work as the buttons.
@skiadas

**Comment by skiadas** [comment]
You need to add to each svg a data-attribute with the corresponding button. If you have them both in some arrays in main.js, you should be able to add the relations. Then when a click occurs, you access that data attribute, and then trigger a click on the corresponding button. That would be one way at least.

**Comment by LukeLentz** [comment]
I've tried setting data attributes in a for loop, but I'm not sure if I'm doing correctly. The console log for select string is not called when I try to click on one of the strings in the svg graphic.
@skiadas

**Comment by skiadas** [comment]
Where are you adding the handler for clicks on the svg elements?

**Comment by LukeLentz** [comment]
I need to add it to draw, right? I can add a .on('click'), but how do I let it know about selectString?
@skiadas

**Comment by skiadas** [comment]
You should be able to add it to draw, yes. The handler itself should be able to find the actual target of the event, you may have to look at the docs or the argument values at least, usually the first or second argument is a rich event object. Once you have the target, it should have a data attribute that is the corresponding string. You get that data attribute out and hopefully call an appropriate method on it.

**Comment by LukeLentz** [comment]
selectString only takes ev as an argument. When I try to append 
.on('click', selectString(theStrings.dataset.string));
to draw, I get the error
Uncaught TypeError: Cannot read property 'on' of undefined
@skiadas

**Comment by LukeLentz** [comment]
Here is what I have now:
    var draw = SVG("drawing").size(533, 104);
    draw.click(function(){
        selectString(theStrings.dataset.string);
    });
If I make the function something like a console log, it works, but I don't know how to define selectString
@skiadas

**Comment by skiadas** [comment]
Hm ok I think you are trying to directly run the handler that you had in place for clicking the buttons. That's not what I had in mind.

What I thought you would do is, in the handler for the click, find the button corresponding to the same string/fret, then trigger a click event on that button. So your selectString handler will then run in response to that click, just how it does now when you manually click the buttons.

The alternative is to rewrite selectString so that it doesn't really depend on "ev" directly, rather only on the fret/string combination. Then you would need to do more work in your button handler, but then your svg handler might be able to call selectString somewhat directly.

Not sure if that helps. It all depends on to what extent you previously separated the code in appropriate places.
