### ISSUE TITLE
svg is sometimes not defined

### ISSUE THREAD

**Issue by LukeLentz** [FlynnHorrell/WebAppsProject#9]
Sometimes the console shows svg as undefined, and the graphics do not appear on the screen. Reloading the page one or two times fixes this. 

@skiadas

**Comment by skiadas** [comment]
You are executing the function that draws  at the bottom of drawing.js, you should not do that there. This will cause trouble because you don't know at what time that occurs relatively to when the page will be ready. The drawing.js file should just return a function (or the function wrapped in an object that you have there).

The only place you know the page is ready is lines 38-44 of main.js. Anything that you want to do to the page needs to be called there. It is here that you should be calling the function obtained from drawing.js
